name: soil_mobile_app
description: Mobile frontend for the Surigao City soil decision-support capstone.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
